// <auto-generated />
namespace Exam.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adminservicev2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adminservicev2));
        
        string IMigrationMetadata.Id
        {
            get { return "201604290117137_admin servicev2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
